/*
 * Copyright 2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.sourcegen.generator.visitors;

import io.micronaut.core.annotation.AnnotationValue;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.naming.NameUtils;
import io.micronaut.inject.ast.ClassElement;
import io.micronaut.inject.ast.EnumConstantElement;
import io.micronaut.inject.ast.EnumElement;
import io.micronaut.inject.ast.PropertyElement;
import io.micronaut.inject.visitor.VisitorContext;
import io.micronaut.sourcegen.annotations.PluginTaskParameter;
import io.micronaut.sourcegen.annotations.PluginTaskParameter.OutputType;
import io.micronaut.sourcegen.annotations.PluginTaskParameter.PathSensitivity;
import io.micronaut.sourcegen.generator.visitors.JavadocUtils.TypeJavadoc;
import io.micronaut.sourcegen.generator.visitors.PluginUtils.ParameterConfig;
import io.micronaut.sourcegen.model.ClassDef;
import io.micronaut.sourcegen.model.ClassDef.ClassDefBuilder;
import io.micronaut.sourcegen.model.ClassTypeDef;
import io.micronaut.sourcegen.model.EnumDef;
import io.micronaut.sourcegen.model.EnumDef.EnumConstantDef;
import io.micronaut.sourcegen.model.EnumDef.EnumDefBuilder;
import io.micronaut.sourcegen.model.ExpressionDef;
import io.micronaut.sourcegen.model.ExpressionDef.ComparisonOperation.OpType;
import io.micronaut.sourcegen.model.ExpressionDef.MathBinaryOperation;
import io.micronaut.sourcegen.model.FieldDef;
import io.micronaut.sourcegen.model.FieldDef.FieldDefBuilder;
import io.micronaut.sourcegen.model.MethodDef;
import io.micronaut.sourcegen.model.ObjectDef;
import io.micronaut.sourcegen.model.ParameterDef;
import io.micronaut.sourcegen.model.PropertyDef;
import io.micronaut.sourcegen.model.PropertyDef.PropertyDefBuilder;
import io.micronaut.sourcegen.model.StatementDef;
import io.micronaut.sourcegen.model.TypeDef;
import io.micronaut.sourcegen.model.VariableDef;
import io.micronaut.sourcegen.model.VariableDef.Local;

import javax.lang.model.element.Modifier;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * A utility class for building models.
 */
@Internal
public class ModelBuilder {

    protected static final String CONVERT_METHOD_PREFIX = "convert";
    protected final Map<String, List<ParameterConfig>> pojoParametersCache = new LinkedHashMap<>();
    protected final Map<String, GeneratedModel> generatedModels = new LinkedHashMap<>();
    protected final String packageName;

    /**
     * Create the model builder.
     * @param packageName The package name to use for new created models
     */
    public ModelBuilder(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Get all the models generated by this builder.
     * @return The models
     */
    public Collection<GeneratedModel> getGeneratedModels() {
        return generatedModels.values();
    }

    /**
     * Get configuration for a plugin parameter.
     *
     * @param sourceJavadoc The javadoc for the task type
     * @param property The property representing the parameter
     * @return THe configuration
     */
    public @NonNull PluginUtils.ParameterConfig getParameterConfig(
        @NonNull VisitorContext context,
        @NonNull JavadocUtils.TypeJavadoc sourceJavadoc,
        @NonNull PropertyElement property
    ) {
        AnnotationValue<PluginTaskParameter> annotation = property.getAnnotation(PluginTaskParameter.class);
        String javadoc = sourceJavadoc.elements().get(property.getName());
        if (javadoc == null) {
            javadoc = "Configurable " + property.getName() + " parameter.";
        }
        TypeDef type = getType(context, property.getType());
        boolean isPojo = ModelUtils.isPOJO(property.getType());
        if (annotation == null) {
            return new ParameterConfig(
                property,
                false,
                null,
                false,
                false,
                OutputType.NONE,
                javadoc,
                type,
                PathSensitivity.ABSOLUTE,
                isPojo,
                isPojo ? createPojoParameters(context, property.getType()) : Collections.emptyList()
            );
        }
        return new ParameterConfig(
            property,
            annotation.booleanValue("required").orElse(false),
            annotation.stringValue("defaultValue").orElse(null),
            annotation.booleanValue("internal").orElse(false),
            annotation.booleanValue("directory").orElse(false),
            annotation.enumValue("output", OutputType.class).orElse(OutputType.NONE),
            javadoc,
            type,
            annotation.enumValue("pathSensitivity", PathSensitivity.class).orElse(PathSensitivity.ABSOLUTE),
            isPojo,
            isPojo ? createPojoParameters(context, property.getType()) : Collections.emptyList()
        );
    }

    /**
     * Utility method to create parameter configurations for the property.
     * @param context The visitor context
     * @param element The element
     * @return The parameters
     */
    private List<ParameterConfig> createPojoParameters(
        @NonNull VisitorContext context, @NonNull ClassElement element
    ) {
        if (pojoParametersCache.containsKey(element.getName())) {
            return pojoParametersCache.get(element.getName());
        }

        List<ParameterConfig> pojoParameters = new ArrayList<>();
        TypeJavadoc javadoc = JavadocUtils.getTaskJavadoc(context, element);
        for (PropertyElement property: element.getBeanProperties()) {
            pojoParameters.add(getParameterConfig(context, javadoc, property));
        }

        pojoParametersCache.put(element.getName(), pojoParameters);
        return pojoParameters;
    }

    /**
     * A utility method for getting a parameter type.
     * Complex types, like enums and POJOs get copied and re-mapped.
     *
     * @param context the Context
     * @param element The element
     * @return The type
     */
    public TypeDef getType(
            VisitorContext context, ClassElement element
    ) {
        GeneratedModel existing = generatedModels.get(element.getName());
        if (existing != null) {
            return existing.type();
        }
        if (element.isEnum()) {
            context.info("Copying plugin model for enum: " + element.getName());
            return copyEnum(context, element);
        }
        if (ModelUtils.isPOJO(element)) {
            context.info("Copying plugin model for POJO: " + element.getName());
            return copyPOJO(context, element, createPojoParameters(context, element));
        }
        Map<String, ClassElement> typeArgs = element.getTypeArguments();
        if (element.isAssignable(Collection.class) && typeArgs.containsKey("E") && ModelUtils.isModel(typeArgs.get("E"))
        ) {
            return TypeDef.parameterized(ClassTypeDef.of(element.getType()),
                getType(context, typeArgs.get("E")));
        }
        return TypeDef.of(element);
    }

    /**
     * Copy an existing enum to the plugin generated sources.
     *
     * @param context The visitor context
     * @param element The element to copy
     * @return The type of copied enum
     */
    protected ClassTypeDef copyEnum(
            VisitorContext context, ClassElement element
    ) {
        TypeJavadoc javadoc = JavadocUtils.getTaskJavadoc(context, element);
        EnumDefBuilder enumDefBuilder = EnumDef.builder(packageName + "." + getSimpleName(element))
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc(javadoc.javadoc().orElse(element.getName() + " enum."));
        if (element instanceof EnumElement enumElement) {
            for (EnumConstantElement constant: enumElement.elements()) {
                enumDefBuilder.addEnumConstant(
                    EnumConstantDef.builder(constant.getName())
                        .addJavadoc(javadoc.enumConstants().getOrDefault(constant.getName(), constant.getName() + " value"))
                        .build()
                );
            }
        }
        EnumDef enumDef = enumDefBuilder.build();
        ClassTypeDef type = enumDef.asTypeDef();
        generatedModels.put(element.getName(), new GeneratedModel(enumDef, element, convertEnumMethod(type, element), type));
        return type;
    }

    /**
     * Copy an existing POJO to the plugin generated sources.
     *
     * @param context The visitor context
     * @param element The element to copy
     * @return The type of copied POJO
     */
    protected ClassTypeDef copyPOJO(
            VisitorContext context, ClassElement element, List<ParameterConfig> parameters
    ) {
        TypeJavadoc javadoc = JavadocUtils.getTaskJavadoc(context, element);
        ClassDefBuilder classDefBuilder = ClassDef.builder(packageName + "." + getSimpleName(element))
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc(javadoc.javadoc().orElse(element.getName() + " class."))
            .addSuperinterface(TypeDef.of(Serializable.class));
        List<FieldDef> fields = new ArrayList<>();
        for (ParameterConfig parameter: parameters) {
            PropertyElement property = parameter.source();
            FieldDefBuilder fieldDefBuilder = FieldDef.builder(property.getName())
                    .addModifiers(Modifier.PRIVATE)
                    .ofType(parameter.type())
                    .addJavadoc(parameter.javadoc());
            if (parameter.defaultValue() != null) {
                fieldDefBuilder.initializer(PluginUtils.createDefault(parameter.type(), parameter.defaultValue()));
            }
            FieldDef fieldDef = fieldDefBuilder.build();
            fields.add(fieldDef);
            classDefBuilder.addField(fieldDef);
        }
        for (int i = 0; i < fields.size(); i++) {
            String fieldJavadoc = javadoc.elements().get(fields.get(i).getName());
            classDefBuilder.addMethod(createGetter(fields.get(i), fieldJavadoc));
            classDefBuilder.addMethod(createWither(fields, fieldJavadoc, i));
            classDefBuilder.addMethod(createSetter(fields.get(i), fieldJavadoc));
        }
        ClassDef classDef = classDefBuilder
            .addAllFieldsConstructor(Modifier.PUBLIC)
            .addConstructor(Collections.emptyList(), Modifier.PUBLIC)
            .build();
        ClassTypeDef type = classDef.asTypeDef();
        generatedModels.put(element.getName(), new GeneratedModel(
            classDef, element, convertPOJOMethod(type, element, parameters), type
        ));
        return type;
    }

    /**
     * Converts a parameter value if required.
     * Conversion is required if the value is a model, so a new type was generated for it
     * instead of the original one.
     *
     * @param type The type
     * @param name The name to use for local variable
     * @param statements The modifiable statements to which a local variable may be added if needed
     * @param paramExpression The current expression for param
     * @return The new expression for param
     */
    public ExpressionDef convertParameterIfRequired(
        ClassElement type, String name, List<StatementDef> statements, ExpressionDef paramExpression
    ) {
        if (ModelUtils.isModel(type)) {
            ClassTypeDef requiredType = ClassTypeDef.of(type);
            Local param = new Local(name, requiredType);
            String simpleName = getSimpleName(type);
            statements.add(param.defineAndAssign(new VariableDef.This()
                .invoke(CONVERT_METHOD_PREFIX + simpleName, requiredType, paramExpression)));
            return param;
        }
        Map<String, ClassElement> typeArgs = type.getTypeArguments();
        if (type.isAssignable(Collection.class) && typeArgs.containsKey("E") && ModelUtils.isModel(typeArgs.get("E"))) {
            Local param = new Local(name, ClassTypeDef.of(type));
            return convertCollectionParameter(param, typeArgs.get("E"), param, statements, type.isAssignable(Set.class));
        }
        return paramExpression;
    }

    /**
     * Create expression for converting a parameter that is a collection.
     *
     * @param localVar The variable to store to
     * @param arg The type to convert to
     * @param paramExpression The expression for the parameter
     * @param statements The current statements
     * @param isSet Whether the collection is a set
     * @return The expression
     */
    protected ExpressionDef convertCollectionParameter(
        Local localVar, ClassElement arg, ExpressionDef paramExpression, List<StatementDef> statements, boolean isSet
    ) {
        String simpleName = getSimpleName(arg);
        statements.add(localVar.defineAndAssign(ExpressionDef.constant(null)));
        List<StatementDef> innerStatements = new ArrayList<>();
        innerStatements.add(localVar.assign(
            isSet ? ClassTypeDef.of(HashSet.class).instantiate()
                : ClassTypeDef.of(ArrayList.class).instantiate()
        ));
        Local i = new Local("i", TypeDef.primitive(int.class));
        innerStatements.add(i.defineAndAssign(ExpressionDef.constant(0)));
        innerStatements.add(new StatementDef.While(
            i.compare(OpType.LESS_THAN, paramExpression.invoke("size", TypeDef.primitive(int.class))),
            StatementDef.multi(
                localVar.invoke("add", TypeDef.VOID,
                    new VariableDef.This().invoke(CONVERT_METHOD_PREFIX + simpleName, TypeDef.of(arg),
                        paramExpression.invoke("get", TypeDef.OBJECT, i)
                    )
                ),
                i.assign(i.math(MathBinaryOperation.OpType.ADDITION, ExpressionDef.constant(1)))
            )
        ));
        statements.add(new StatementDef.If(paramExpression.compare(OpType.NOT_EQUAL_TO, ExpressionDef.constant(null)), StatementDef.multi(innerStatements)));
        return localVar;
    }

    /**
     * Create a wither method.
     *
     * @param fields The properties
     * @param javadoc The javadoc for property
     * @param index The property index
     * @return The wither method
     */
    protected static MethodDef createWither(List<FieldDef> fields, @Nullable String javadoc, int index) {
        FieldDef field = fields.get(index);
        return MethodDef.builder("with" + NameUtils.capitalize(field.getName()))
            .addJavadoc("Create a copy and set " + field.getName() + "."
                + (javadoc != null ? "\n" + javadoc : "")
            )
            .addParameter(ParameterDef.of(field.getName(), field.getType()))
            .addModifiers(Modifier.PUBLIC)
            .returns(TypeDef.THIS)
            .build((t, params) -> {
                List<ExpressionDef> constructorValues = new ArrayList<>();
                for (int j = 0; j < fields.size(); j++) {
                    if (index == j) {
                        constructorValues.add(params.get(0));
                    } else {
                        constructorValues.add(t.field(
                            fields.get(j).getName(), fields.get(j).getType()
                        ));
                    }
                }
                return new StatementDef.Return(TypeDef.THIS.instantiate(constructorValues));
            });
    }

    /**
     * Create a getter method.
     *
     * @param field The field
     * @param javadoc The javadoc for property
     * @return The getter method
     */
    protected static MethodDef createGetter(FieldDef field, @Nullable String javadoc) {
        return MethodDef.builder("get" + NameUtils.capitalize(field.getName()))
            .addJavadoc("Get " + field.getName() + "." + (javadoc != null ? "\n" + javadoc : ""))
            .addModifiers(Modifier.PUBLIC)
            .returns(field.getType())
            .build((t, params) -> new StatementDef.Return(t.field(field)));
    }

    /**
     * Create a setter method.
     *
     * @param field The field
     * @param javadoc The javadoc for property
     * @return The setter method
     */
    protected static MethodDef createSetter(FieldDef field, @Nullable String javadoc) {
        return MethodDef.builder("set" + NameUtils.capitalize(field.getName()))
            .addJavadoc("Set " + field.getName() + "." + (javadoc != null ? "\n" + javadoc : ""))
            .addModifiers(Modifier.PUBLIC)
            .addParameter(ParameterDef.of(field.getName(), field.getType()))
            .returns(TypeDef.VOID)
            .build((t, params) -> t.field(field).assign(params.get(0)));
    }

    /**
     * Create a method for converting an enum.
     *
     * @param type The generated type to convert from
     * @param requiredType The required type to convert to
     * @return The method definition
     */
    protected static MethodDef convertEnumMethod(TypeDef type, ClassElement requiredType) {
        String simpleName = getSimpleName(requiredType);
        ClassTypeDef outputType = ClassTypeDef.of(requiredType);
        return MethodDef.builder(CONVERT_METHOD_PREFIX + simpleName)
            .returns(TypeDef.of(requiredType))
            .addParameter("value", type)
            .build((t, params) -> new StatementDef.IfElse(
                params.get(0).isNull(),
                ExpressionDef.constant(null).returning(),
                outputType.invokeStatic("valueOf", outputType,
                    params.get(0).invoke("name", TypeDef.STRING)
                ).returning()
            ));
    }

    /**
     * Method to create an expression for converting a property of POJO.
     *
     * @param parameter The parameter configuration information
     * @param statements The statements
     * @param owner The owner of the property
     * @return The expression
     */
    protected ExpressionDef convertPOJOParameter(
        ParameterConfig parameter, List<StatementDef> statements, ExpressionDef owner
    ) {
        PropertyElement property = parameter.source();
        return convertParameterIfRequired(
            property.getType(),
            NameUtils.capitalize(property.getName()) + "Param",
            statements,
            owner.invoke("get" + NameUtils.capitalize(property.getName()), TypeDef.OBJECT)
        );
    }

    /**
     * Create a method to convert a POJO.
     *
     * @param type The generate POJO type to convert from
     * @param requiredType The required type to convert to
     * @param parameters The parameter configurations
     * @return The method definition
     */
    protected MethodDef convertPOJOMethod(ClassTypeDef type, ClassElement requiredType, List<ParameterConfig> parameters) {
        String simpleName = getSimpleName(requiredType);
        return MethodDef.builder(CONVERT_METHOD_PREFIX + simpleName)
            .returns(TypeDef.of(requiredType))
            .addParameter("value", type)
            .build((t, params) -> {
                List<StatementDef> statements = new ArrayList<>();
                Map<String, ExpressionDef> args = new HashMap<>();
                for (ParameterConfig param : parameters) {
                    args.put(param.source().getName(), convertPOJOParameter(param, statements, params.get(0)));
                }
                Local result = PluginUtils.instantiateType(requiredType, "result", args, statements);
                statements.add(result.returning());

                return new StatementDef.IfElse(
                    params.get(0).isNull(),
                    ExpressionDef.constant(null).returning(),
                    StatementDef.multi(statements)
                );
            });
    }

    protected static String getSimpleName(ClassElement element) {
        String simpleName = element.getSimpleName();
        int index = simpleName.indexOf("$");
        if (index >= 0) {
            simpleName = simpleName.substring(index + 1);
        }
        return simpleName;
    }

    /**
     * A record for holding the generated model.
     *
     * @param model The generated model object def
     * @param source The source of the model
     * @param convertorMethod The method that converts model to source
     * @param type The type of the mode
     */
    public record GeneratedModel(
        ObjectDef model,
        ClassElement source,
        MethodDef convertorMethod,
        TypeDef type
    ) {
    }

}
